program task2;
begin
writeln('There were three jovial huntsmen,');
writeln('As I have heard them say,');
writeln('And they would go a-hunting');
writeln('And they would go a-hunting');
readln();
writeln();
writeln('All the day they hunted,');
writeln('And nothing could they find');
writeln('But a ship a-sailing,');
writeln('A-sailing with the wind.');
readln();
writeln();
writeln('One said it was a ship,');
writeln('The other he said nay;');
writeln('The third said it was a house');
writeln('With the chimney blown away.');
readln();
writeln();
writeln('And all the night they hunted,');
writeln('And nothing could they find');
writeln('But the moon a-gliding,');
writeln('A-gliding with the wind.');
readln();
writeln();
writeln('One said it was the moon,');
writeln('The other he said nay;');
writeln('The third said it was a cheese,');
write('And half o');
write(chr(039));
writeln('t cut away.');
readln();
end.
